### ISSUE TITLE
Cannot read property 'test' of undefined

### ISSUE THREAD

**Issue by Heziode** [nuxt-community/svg-module#41]
I get this error when I try to use this module:
```
Cannot read property 'test' of undefined                                                                                                                                                        

  at node_modules/@nuxtjs/svg/lib/module.js:23:51
  at Array.filter (<anonymous>)
  at WebpackBundler.setup (node_modules/@nuxtjs/svg/lib/module.js:23:26)
  at WebpackBundler.<anonymous> (node_modules/@nuxt/utils/dist/utils.js:1824:25)
  at WebpackBundler.<anonymous> (node_modules/@nuxt/utils/dist/utils.js:1819:27)
  at WebpackClientConfig.extendConfig (node_modules/@nuxt/webpack/dist/webpack.js:4744:37)
  at WebpackClientConfig.config (node_modules/@nuxt/webpack/dist/webpack.js:4779:45)
  at WebpackClientConfig.config (node_modules/@nuxt/webpack/dist/webpack.js:4934:26)
  at WebpackBundler.getWebpackConfig (node_modules/@nuxt/webpack/dist/webpack.js:5215:19)
  at WebpackBundler.build (node_modules/@nuxt/webpack/dist/webpack.js:5222:12)
  at Builder.build (node_modules/@nuxt/builder/dist/builder.js:5598:30)
  at async Object._buildDev (node_modules/@nuxt/cli/dist/cli-dev.js:98:5)
  at async Object.startDev (node_modules/@nuxt/cli/dist/cli-dev.js:56:7)
  at async Object.run (node_modules/@nuxt/cli/dist/cli-dev.js:43:5)
  at async NuxtCommand.run (node_modules/@nuxt/cli/dist/cli-command.js:2575:7
```

@nuxtjs/svg: 0.1.7

**Comment by brhx** [comment]
Please could you create a reproduction link with the latest version?

**Comment by Heziode** [comment]
Reproduced with latest verison (0.1.10): see my repo [FOE-Tools, branch bug/nuxt-svg-module](https://github.com/Heziode/FOE-Tools.github.io/tree/bug/nuxt-svg-module).

**Comment by Heziode** [comment]
Reopen due to a miss click :joy:

**Comment by brhx** [comment]
Ah OK, so you have a loader in your configuration without a file path testing parameter:

```js
{
  resourceQuery: /blockType=router/,
  loader: "@nuxtjs/router-extras/lib/loader.js",
}
```

I've just pushed `v0.1.11` that should fix it when this condition is met :)

**Comment by Heziode** [comment]
Yep, this works \o/
