### ISSUE TITLE
nuxt-svg: Unexpected '.svg' rule in the webpack configuration

### ISSUE THREAD

**Issue by jwv** [nuxt-community/svg-module#58]
### Versions
nuxt: v2.14.4
node: v14.8.0

### Reproduction
Additional Details
{ mode: 'universal', target: 'static', modules: [ '@nuxtjs/svg' ] }

### Steps to reproduce
Run command nuxt dev or nuxt generate

### What is Expected?
Success

### What is actually happening?
ERROR nuxt-svg: Unexpected '.svg' rule in the webpack configuration

**Comment by ceigh** [comment]
Same issue.

`nuxt`: `2.14.4`
`node`: `v14.8.0`

Can't `dev` or `generate`. `mode: 'spa', target: 'static'`.

Error: 
```
 ERROR  nuxt-svg: Unexpected '.svg' rule in the webpack configuration                                                                20:31:14

  at WebpackBundler.setup (node_modules/@nuxtjs/svg/lib/module.js:30:13)
  at WebpackBundler.<anonymous> (node_modules/@nuxt/utils/dist/utils.js:1868:25)
  at WebpackBundler.<anonymous> (node_modules/@nuxt/utils/dist/utils.js:1863:27)
  at WebpackClientConfig.extendConfig (node_modules/@nuxt/webpack/dist/webpack.js:4881:37)
  at WebpackClientConfig.config (node_modules/@nuxt/webpack/dist/webpack.js:4916:45)
  at WebpackClientConfig.config (node_modules/@nuxt/webpack/dist/webpack.js:5116:26)
  at WebpackBundler.getWebpackConfig (node_modules/@nuxt/webpack/dist/webpack.js:5424:19)
  at WebpackBundler.build (node_modules/@nuxt/webpack/dist/webpack.js:5431:12)
  at Builder.build (node_modules/@nuxt/builder/dist/builder.js:5643:30)
  at async Object._buildDev (node_modules/@nuxt/cli/dist/cli-dev.js:106:5)
  at async Object.startDev (node_modules/@nuxt/cli/dist/cli-dev.js:64:7)
  at async Object.run (node_modules/@nuxt/cli/dist/cli-dev.js:51:5)
  at async NuxtCommand.run (node_modules/@nuxt/cli/dist/cli-index.js:2810:7)
```

**Comment by emmanuelsw** [comment]
Fixed in #57.

**Comment by ceigh** [comment]
I think it can be closed

**Comment by jwv** [comment]
It's fixed it can be closed.

**Comment by kgnfth** [comment]
same issue 
```
"nuxt": "^2.15.2",
"@nuxtjs/svg": "^0.1.12",
```
yarn dev
```js
 ERROR  nuxt-svg: Unexpected '.svg' rule in the webpack configuration

  at WebpackBundler.setup (node_modules/@nuxtjs/svg/lib/module.js:32:13)
  at next (node_modules/@nuxt/utils/dist/utils.js:658:27)
  at WebpackBundler.<anonymous> (node_modules/@nuxt/utils/dist/utils.js:673:12)
  at WebpackBundler.<anonymous> (node_modules/@nuxt/utils/dist/utils.js:667:29)
  at WebpackClientConfig.extendConfig (node_modules/@nuxt/webpack/dist/webpack.js:1507:37)
  at WebpackClientConfig.config (node_modules/@nuxt/webpack/dist/webpack.js:1542:50)
  at WebpackClientConfig.config (node_modules/@nuxt/webpack/dist/webpack.js:1706:26)
  at WebpackBundler.getWebpackConfig (node_modules/@nuxt/webpack/dist/webpack.js:2014:19)
  at WebpackBundler.build (node_modules/@nuxt/webpack/dist/webpack.js:2021:12)
  at Builder.build (node_modules/@nuxt/builder/dist/builder.js:327:30)
  at async Object._buildDev (node_modules/@nuxt/cli/dist/cli-dev.js:107:5)
  at async Object.startDev (node_modules/@nuxt/cli/dist/cli-dev.js:65:7)
  at async Object.onWatchRestart (node_modules/@nuxt/cli/dist/cli-dev.js:136:5)
  at async Nuxt.callHook (node_modules/hable/dist/hable.js:1:959)
  at async FSWatcher.<anonymous> (node_modules/@nuxt/builder/dist/builder.js:924:9)
```

**Comment by ovsw** [comment]
getting the same thing as @kgnfth

**Comment by ovsw** [comment]
actually, the error only appears when using both `@nuxtjs/svg-sprite` and `@nuxtjs/svg`. When only using one of them there's no error.

**Comment by Tobeyforce** [comment]
I get this error when using nuxt-optimized-images

**Comment by wokalek-work** [comment]
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
